### ISSUE TITLE
GPS的XYZ三维的postion进行GPS先验因子约束的代码会放出来吗？

### ISSUE THREAD

**Issue by cudnn** [kahowang/FAST_LIO_SAM#1]
GPS的XYZ三维的postion进行GPS先验因子约束的代码会放出来吗？大概什么时间能弄好？

您添加的算法运行过程中卫星信号中断10分钟以上能再回复，会不会有问题？
运行过程中雷达信号消失（无人机高度超过雷达探测距离）、可以继续使用卫星里程计工作吗？
无人机飞行一段距离后再回到雷达探测范围的高度，雷达里程计还能恢复工作吗？

**Comment by cudnn** [comment]
我是科马（南京）航空科技有限公司 于志庆 。主要生产100-200公斤燃油无人机，在使用激光雷达导航方面遇到一些问题，敬请指教。

**Comment by cudnn** [comment]
https://github.com/hku-mars/dyn_small_obs_avoidance
港大的这组代码  把fast lio   、建图 、fast planner 、飞机控接口都做好了。我想用FAST_LIO_SAM 代替 fats lio，可以给些知道意见吗？

**Comment by kahowang** [comment]
> https://github.com/hku-mars/dyn_small_obs_avoidance 港大的这组代码 把fast lio 、建图 、fast planner 、飞机控接口都做好了。我想用FAST_LIO_SAM 代替 fats lio，可以给些知道意见吗？

FAST-LIO-SAM还处于beta版本，而且加上后端优化后的FAST-LIO，建图效率方面会大大降低。
