### ISSUE TITLE
运行速度很慢

### ISSUE THREAD

**Issue by wszhy525** [kahowang/FAST_LIO_SAM#10]
rviz点云速度和rosbag播放速度相比慢很多，想知道在那出问题的

**Comment by wienans** [comment]
Hi i have the same issue.
The Algorithm does not run in real time output frequency is around 2 Hz with input of 10 Hz (the LIO-SAM Dataset)
I measured some times
[ INFO] [1668499527.975176754]: Before Viz Map: 0.175287 (before line if (visulize_IkdtreeMap))
[ INFO] [1668499528.127812689]: ISAM update: 0.327915 (before line getCurPose(state_point);)
[ INFO] [1668499528.139564854]: Debug: 0.339669 (before line if (runtime_pos_log))
[ INFO] [1668499528.139605012]: End: 0.339731
Therefore the most time is needed for the FAST_LIO Step

**Comment by kahowang** [comment]
cmakelists 中为了减少编译的时间，所以把优化编译注释了，可以在cmakelists中打开  set( CMAKE_CXX_FLAGS "-std=c++14 -O3" )  这一部分~

**Comment by wienans** [comment]
Sorry for inconvenience surely we should have seen this.
Works fine thanks :)
