### ISSUE TITLE
遇到几个代码错误

### ISSUE THREAD

**Issue by ChunqiuYang** [kahowang/FAST_LIO_SAM#11]
1. error: ‘updatePath’ does not name a type
  306 | float globalMapVisualizationLeafSize;updatePath
2.  error: ‘srvSaveMap’ was not declared in this scope; did you mean ‘saveMap’?
 2291 |     srvSaveMap  = nh.advertiseService("/save_map" ,  &saveMapService);
      |     ^~~~~~~~~~
      |     saveMap

我看了源代码，发现上面也有这两个错误。

**Comment by ChunqiuYang** [comment]
删除了第一个代码错误后，第二个报错没有了，您这个看可以更新一下这个代码错误。

**Comment by kahowang** [comment]
ok,非常感谢大佬的指正，代码有不少的bug，之前还没有时间回复，抱歉~

**Comment by kahowang** [comment]
根据大家问题，更新日志如下，后续持续更新，谢谢大家~
https://github.com/kahowang/FAST_LIO_SAM/blob/master/%E6%9B%B4%E6%96%B0%E6%97%A5%E5%BF%97.md
