### ISSUE TITLE
成功编译代码，但提供的demo数据无法成功测试

### ISSUE THREAD

**Issue by astronaunt** [kahowang/FAST_LIO_SAM#12]
您好，感谢您出色的工作！ 我成功编译了您的代码。
在测试Quick test中1 .For indoor dataset的数据时，
运行`roslaunch fast_lio_sam mapping_velodyne16.launch`后成功启动rviz，
放包`rosbag play  T3F2-2021-08-02-15-00-12.bag`  后，
rviz中没有任何结果显示，终端中显示以下内容，且包的内容一直在放，但终端中没有任何消息更新。
```
setting /run_id to 2d935e86-b141-11ed-bb7a-90ccdfb6eca7
process[rosout-1]: started with pid [18496]
started core service [/rosout]
process[laserMapping-2]: started with pid [18503]
process[rviz-3]: started with pid [18504]
Multi thread started 
p_pre->lidar_type 2
~~~~/home/astronaut/WorkSpace_own/FAST_LIO_SAM_test/src/FAST_LIO_SAM/FAST_LIO_SAM/ file opened
[ INFO] [1676912969.364559491]: IMU Initial Done
[ WARN] [1676912969.365444107]: No point, skip this scan!
```
我核对了lidar和imu的topic类型，没有问题，我寻找不到哪里出错，如果您能提供任何帮助，不胜感激，再次感谢！

**Comment by kahowang** [comment]
不好意思，单靠上面的信息，我暂时也无法定位题所在，可以debug一下工程里的点云回调函数看看~

**Comment by AbelSyx** [comment]
请问你解决这个问题了吗？ @astronaunt

**Comment by AbelSyx** [comment]
你是在ROS noetic环境下编译的吗？我发现ROS melodic可以正常运行

**Comment by zeratul824** [comment]
check the gtsam installed correct
