### ISSUE TITLE
代码成功编译运行，但是使用vscode打开该项目laserMapping.cpp和IMU_Processing.hpp代码无法补全，出错也没有红色波浪线

### ISSUE THREAD

**Issue by liujian123223** [kahowang/FAST_LIO_SAM#13]
代码成功编译运行，想要自己修改某些内容，但是使用vscode打开该项目laserMapping.cpp和IMU_Processing.hpp代码无法补全，出错也没有红色波浪线，但preprocess.cpp可以补全代码，不知道是不是头文件的问题，请问作者遇到过这种情况吗？

**Comment by heroacool** [comment]
.vscode/c_cpp_properties.json中修改includePath
