### ISSUE TITLE
GPS position

### ISSUE THREAD

**Issue by songWell** [kahowang/FAST_LIO_SAM#17]
您好，我刚开始学习slam，您的工作给了我很大的帮助，我有以下疑问，如果您能帮忙解答，不胜感激。
请问GPSfactor的position是在东北天坐标系下的，状态变量是在初始帧的坐标系下的，这样没有影响吗？
还是说一开始这两个是在不同坐标系下的，但初始建图阶段，地图就从lidar坐标系转换到东北天坐标系下。

**Comment by kahowang** [comment]
你好，非常感谢你的关注。一般来说，GPS获取的经纬高信息是84坐标，在本工程中，通过使用Geographlib库，将位置信息从84坐标系转换到ENU东北天系下。对于LIO-SLAM系统，状态变量都是在初始帧下的，所以GPS 获取的ENU下的位置信息与LIO系统获取的位置信息，存在一定的航向偏差。一般需要进行ENU 与 World 外参标定(常用绕八字的方式)，但是在本工程中，并没有进行预先的标定，因为即使存在航向的偏差，ISAM2后端会进行航向的纠正，LIO系统的轨迹航向会慢慢纠正到ENU系下(如工程中户外数据集航向实验所示)。
再次感谢关注，Kaho 2023.5.6

**Comment by songWell** [comment]
谢谢您的回复！
