### ISSUE TITLE
livox mid70雷达使用gps

### ISSUE THREAD

**Issue by HM-Lii** [kahowang/FAST_LIO_SAM#21]
我使用的是livox mid70雷达，可以运行fast_lio2，但您的功能包中config文件avia.yaml中没有关于gps的设置，如果要使用gps，应如何设置？

**Comment by kahowang** [comment]
你好，非常感谢你的关注。GPS我实用的是自己的接收机(兴网宇达M2)和一些数据集提供的GPS数据，因为不同GPS的实用方式都不一样(有一些需要自己编写驱动)，所以没有提供GPS的具体设置方式。而代码中，对接入GPS数据的处理是，读取第一帧的UTM下的经纬高数据，然后进行ENU的转换。谢谢~
