### ISSUE TITLE
提示说需要livox的驱动，为什么还需要驱动呢

### ISSUE THREAD

**Issue by zhao-zhibo** [kahowang/FAST_LIO_SAM#28]
- Using these message generators: gencpp;geneus;genlisp;gennodejs;genpy
-- Could NOT find livox_ros_driver (missing: livox_ros_driver_DIR)
-- Could not find the required component 'livox_ros_driver'. The following CMake error indicates that you either need to install the package with the same name or change your environment so that it can be found.
CMake Error at /opt/ros/noetic/share/catkin/cmake/catkinConfig.cmake:83 (find_package):
  Could not find a package configuration file provided by "livox_ros_driver"

**Comment by kahowang** [comment]
你好，非常感谢你的关注，因为baseline FASTLIO算法对livox雷达兼容，而livox驱动package里包含livox msg的一些头文件，所以需要把livox_ros_driver 放到对应的工作空间中，进行一起编译。 谢谢~

**Comment by zhao-zhibo** [comment]
感谢回复和代码的贡献，已经编译了livox的驱动并成功编译fastlio-sam的代码



> 你好，非常感谢你的关注，因为baseline FASTLIO算法对livox雷达兼容，而livox驱动package里包含livox msg的一些头文件，所以需要把livox_ros_driver 放到对应的工作空间中，进行一起编译。 谢谢~

**Comment by kahowang** [comment]
好的，谢谢关注~
