### ISSUE TITLE
rviz中点云更新很慢 & 程序报错

### ISSUE THREAD

**Issue by InterKnight** [kahowang/FAST_LIO_SAM#4]
你好，感谢你开源这个项目，我在用 mid 70 建图时发现两个问题：
1，rviz中的点云更新很慢，比实际要延迟5s以上
2，程序运行到一定时间就报错，并且没有找到相关的报错日志，详情如下，请问有解决办法吗？

... logging to /home/lin/.ros/log/2a0d6948-097e-11ed-bd7f-c8f7504e8e86/roslaunch-lin-Latitude-5490-18848.log
Checking log directory for disk usage. This may take a while.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://lin-Latitude-5490:36025/

SUMMARY
========

PARAMETERS
 * /common/imu_topic: /handsfree/imu
 * /common/lid_topic: /livox/lidar
 * /common/time_sync_en: False
 * /cube_side_length: 1000.0
 * /feature_extract_enable: False
 * /filter_size_map: 0.5
 * /filter_size_surf: 0.5
 * /mapping/acc_cov: 0.1
 * /mapping/b_acc_cov: 0.0001
 * /mapping/b_gyr_cov: 0.0001
 * /mapping/det_range: 450.0
 * /mapping/extrinsic_R: [1, 0, 0, 0, 1, 0...
 * /mapping/extrinsic_T: [0.008, 0.01, -0.08]
 * /mapping/extrinsic_est_en: False
 * /mapping/fov_degree: 70
 * /mapping/gyr_cov: 0.1
 * /max_iteration: 3
 * /pcd_save/interval: -1
 * /pcd_save/pcd_save_en: True
 * /point_filter_num: 4
 * /preprocess/blind: 4
 * /preprocess/lidar_type: 1
 * /preprocess/scan_line: 6
 * /publish/dense_publish_en: True
 * /publish/path_en: True
 * /publish/scan_bodyframe_pub_en: True
 * /publish/scan_publish_en: True
 * /rosdistro: melodic
 * /rosversion: 1.14.10
 * /runtime_pos_log_enable: False

NODES
  /
    laserMapping (fast_lio_sam/fastlio_sam_mapping)
    rviz (rviz/rviz)

ROS_MASTER_URI=http://localhost:11311

process[laserMapping-1]: started with pid [18875]
process[rviz-2]: started with pid [18876]
Multi thread started 
p_pre->lidar_type 1
~~~~/home/lin/catkin_ws/src/FAST_LIO_SAM/FAST_LIO_SAM/ file opened
[ WARN] [1658470269.904093606]: No point, skip this scan!

[ INFO] [1658470270.002792391]: IMU Initial Done
[ WARN] [1658470270.002894994]: No point, skip this scan!

[ INFO] [1658470315.040993040]: Find loop clousre frame 
[laserMapping-1] process has died [pid 18875, exit code -11, cmd /home/lin/catkin_ws/devel/lib/fast_lio_sam/fastlio_sam_mapping __name:=laserMapping __log:=/home/lin/.ros/log/2a0d6948-097e-11ed-bd7f-c8f7504e8e86/laserMapping-1.log].
log file: /home/lin/.ros/log/2a0d6948-097e-11ed-bd7f-c8f7504e8e86/laserMapping-1*.log

**Comment by kahowang** [comment]
1.你好关于rviz显示很慢的问题，可能是由于内存太大，因为我之前测试的数据及都是基于VLP16或者VLP32，livox雷达相对来说点云密度很大，可能会导致内存不够。包括之前FASTLIO2也RVIZ显示也存在这个问题，FASTLIO-SAM加上后端的部分后，实时性也会受到一定的削弱。可以关闭RVIZ，然后最后保存地图先看看效果。
2.关于程序运行到一定的时间会报错，请问数据集大概是多大呢，我之前也遇到过这个问题，是数据集太大的原因，后续会去排查这个问题，更新。
3.如果方便的话，可以告诉我你的具体采集数据集设备吗？
4.谢谢你的关注~

**Comment by InterKnight** [comment]
> 

你好，感谢建议，我关掉rviz试一试。我是连外设实时建图，用的 mid 70 和 taobotics的IMU

**Comment by InterKnight** [comment]
> > > 
> > 
> > 
> > 你好，感谢建议，我关掉rviz试一试。我是连外设实时建图，用的 mid 70 和 taobotics的IMU
> 
> 建议可以，先把你的数据集在FASTLIO2试试，因为FASTLIO-SAM的前端里程计部分是摘自FASTLIO2喔~

你好，这个试过是可以的

**Comment by kahowang** [comment]
> > > > 
> > > 
> > > 
> > > 你好，感谢建议，我关掉rviz试一试。我是连外设实时建图，用的 mid 70 和 taobotics的IMU
> > 
> > 
> > 建议可以，先把你的数据集在FASTLIO2试试，因为FASTLIO-SAM的前端里程计部分是摘自FASTLIO2喔~
> 
> 你好，这个试过是可以的

好的，方便的话，你可以发个联系方式我，后续交流一下，谢谢。

**Comment by InterKnight** [comment]
> > > > > 
> > > > 
> > > > 
> > > > 你好，感谢建议，我关掉rviz试一试。我是连外设实时建图，用的 mid 70 和 taobotics的IMU
> > > 
> > > 
> > > 建议可以，先把你的数据集在FASTLIO2试试，因为FASTLIO-SAM的前端里程计部分是摘自FASTLIO2喔~
> > 
> > 
> > 你好，这个试过是可以的
> 
> 好的，方便的话，你可以发个联系方式我，后续交流一下，谢谢。

私信你CSDN了

**Comment by kahowang** [comment]
已解决~

**Comment by yijing2050** [comment]
我也发现特别是运动过的物体在rviz里形成一个立方体，很久才消失，即rviz中的点云更新很慢，这样有点影响建图视觉和效率。

> 已解决~

**Comment by Eric-Zhao1** [comment]
> 1.你好关于rviz显示很慢的问题，可能是由于内存太大，因为我之前测试的数据及都是基于VLP16或者VLP32，livox雷达相对来说点云密度很大，可能会导致内存不够。包括之前FASTLIO2也RVIZ显示也存在这个问题，FASTLIO-SAM加上后端的部分后，实时性也会受到一定的削弱。可以关闭RVIZ，然后最后保存地图先看看效果。 2.关于程序运行到一定的时间会报错，请问数据集大概是多大呢，我之前也遇到过这个问题，是数据集太大的原因，后续会去排查这个问题，更新。 3.如果方便的话，可以告诉我你的具体采集数据集设备吗？ 4.谢谢你的关注~

你好，请问数据集太大导致程序运行一段时间报错，这个问题是怎么解决的呢？我自己的测试数据集380G左右。

**Comment by SabraHashemi** [comment]
**I've encountered the same problem here, did you solve it?**

> Regarding the error message after the program runs for a certain period of time, how big is the data set? I have encountered this problem before. It is because the data set is too large. I will investigate this problem and update it later.
