### ISSUE TITLE
因为GTSAM的问题编译不过 catkin_package() DEPENDS on 'GTSAM' but neither 'GTSAM_INCLUDE_DIRS' nor   'GTSAM_LIBRARIES' is defined.

### ISSUE THREAD

**Issue by HP-Yin** [kahowang/FAST_LIO_SAM#6]
-- fast_lio_sam: 1 messages, 2 services
CMake Warning at /opt/ros/noetic/share/catkin/cmake/catkin_package.cmake:166 (message):
  catkin_package() DEPENDS on 'GTSAM' but neither 'GTSAM_INCLUDE_DIRS' nor
  'GTSAM_LIBRARIES' is defined.
Call Stack (most recent call first):
  /opt/ros/noetic/share/catkin/cmake/catkin_package.cmake:102 (_catkin_package)
  FAST_LIO_SAM/FAST_LIO_SAM/CMakeLists.txt:102 (catkin_package)
-- Configuring incomplete, errors occurred!
See also "/home/yhp/ProjectRaw/fast_lio_sam_ws/build/CMakeFiles/CMakeOutput.log".
See also "/home/yhp/ProjectRaw/fast_lio_sam_ws/build/CMakeFiles/CMakeError.log".
Invoking "cmake" failed

**Comment by kahowang** [comment]
你好，提示找不到GTSAM库，装一下吧~

**Comment by lonlonago** [comment]
安装了GTSAM 还是报这个错误，我编译lio sam 不会报错

**Comment by lonlonago** [comment]
安装了GTSAM 还是报这个错误，我编译lio sam 不会报错

**Comment by HP-Yin** [comment]
> 安装了GTSAM 还是报这个错误，我编译lio sam 不会报错

我也遇到了这种情况，把里面的livox_ros_driver删掉就i好了

**Comment by lonlonago** [comment]
另外，我用livox 数据测试了一下，完全没有里程计的结果。。。就是原地扫描。。不知道啥情况

**Comment by lonlonago** [comment]
> > 安装了GTSAM 还是报这个错误，我编译lio sam 不会报错
> 
> 我也遇到了这种情况，把里面的livox_ros_driver删掉就i好了

是的，我刚刚也发现了，删除掉就好了；  很奇怪的问题；  但是发现好像不支持livox数据？ 我改了launch 文件，用livox 数据，跑的过程很奇怪，完全没有建图

**Comment by kahowang** [comment]
不好意思，下午在忙，没回复到，之前有小伙伴用mid-70自己的数据集尝试过，可以成功建图，我也用他的数据集试试。暂时无法通过你们说的现象去定位问题，可以详细描述一下过程、设备吗，或者留个联系方式？

**Comment by lonlonago** [comment]
谢谢了，微信 394467238  ，可以发bag 给你哈

**Comment by lonlonago** [comment]
> > 谢谢了，微信 394467238 ，可以发bag 给你哈
> 
> 收到~

老哥，加我了吗。。

**Comment by kahowang** [comment]
> > > 谢谢了，微信 394467238 ，可以发bag 给你哈
> > 
> > 
> > 收到~
> 
> 老哥，加我了吗。。

好的，不好意思，最近在准备面试，miss了~

**Comment by lyg446332675** [comment]
你好，我刚接触这方面，请问livox_ros_driver是在哪个里面呀，没找到在哪

> > 安装了GTSAM 还是报这个错误，我编译lio sam 不会报错
> 
> 我也遇到了这种情况，把里面的livox_ros_driver删掉就i好了

你好，我刚接触这方面，请问livox_ros_driver是在哪个里面呀
