### ISSUE TITLE
livox_avia?

### ISSUE THREAD

**Issue by JasonWang9805** [kahowang/FAST_LIO_SAM#8]
我在建图过程中会有延迟建图现象，想问下作者知道这是在哪部分的问题吗

**Comment by kahowang** [comment]
是因为cmakelists中把编译优化注解了，详情见更新日志。实在在不好意思，回复晚了~https://github.com/kahowang/FAST_LIO_SAM/blob/master/%E6%9B%B4%E6%96%B0%E6%97%A5%E5%BF%97.md
