### ISSUE TITLE
how to save map

### ISSUE THREAD

**Issue by wolf943134497** [kahowang/FAST_LIO_SAM#9]
Hi @kahowang  Thanks for your great works!
when I save the map, some error occurs:
rosservice call /save_map "resolution: 0.0 destination: ''"
ERROR: Unable to load type [fast_lio_sam/save_map].
Have you typed 'make' in [fast_lio_sam]?

any suggestions? Thanks a lot!

**Comment by kahowang** [comment]
Sorry for the late reply. Have you solved the problem now~

**Comment by GuoYongyu** [comment]
I have the same question too.

**Comment by kahowang** [comment]
> I have the same question too.

Ok, Thanks yo your attention.
1. source devel/setup.bash 
2. copy this to your termianl   

rosservice call /save_map "resolution: 0.0
destination: ''" 
success: True

**Comment by GuoYongyu** [comment]
But the question is that your command has two lines, copying the command to terminal will be wrong.

And I have a new question that if I want to run with my own dataset, which launch file should I use?
